package question.adder;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.Timer;


     // TODO add your handling code here:


/**
 *
 * @author hopek
 */
public class QUIZ extends javax.swing.JFrame {
    int sec=15;
    Timer timer;
    
    
    /**
     * Creates new form NewJFrame
     */
    public QUIZ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        tf2 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();
        b31 = new javax.swing.JButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        lsec = new javax.swing.JLabel();
        b32 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("JO JEETA WAHI SIKANDER");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("QUESTION CATEGORY");

        bg1.add(rb1);
        rb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb1.setText("INDORE");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        bg1.add(rb2);
        rb2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb2.setText("Madhya Pradesh");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        bg1.add(rb3);
        rb3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb3.setText("INDIA");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        bg1.add(rb4);
        rb4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb4.setText("Miscellaneous");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("QUESTION");

        b1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b1.setText("Q1");
        b1.setEnabled(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b2.setText("Q2");
        b2.setEnabled(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b3.setText("Q3");
        b3.setEnabled(false);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b4.setText("Q4");
        b4.setEnabled(false);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b5.setText("Q5");
        b5.setEnabled(false);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b6.setText("Q6");
        b6.setEnabled(false);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b7.setText("Q7");
        b7.setEnabled(false);
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b8.setText("Q8");
        b8.setEnabled(false);
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b9.setText("Q9");
        b9.setEnabled(false);
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b10.setText("Q10");
        b10.setEnabled(false);
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b11.setText("Q11");
        b11.setEnabled(false);
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b12.setText("Q12");
        b12.setEnabled(false);
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b13.setText("Q13");
        b13.setEnabled(false);
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b14.setText("Q14");
        b14.setEnabled(false);
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b15.setText("Q15");
        b15.setEnabled(false);
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b16.setText("Q16");
        b16.setEnabled(false);
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        b17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b17.setText("Q17");
        b17.setEnabled(false);
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });

        b18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b18.setText("Q18");
        b18.setEnabled(false);
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });

        b19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b19.setText("Q19");
        b19.setEnabled(false);
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });

        b20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b20.setText("Q20");
        b20.setEnabled(false);
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });

        b21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b21.setText("Q21");
        b21.setEnabled(false);
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("QUESTION NUMBER");

        t1.setEditable(false);
        t1.setColumns(20);
        t1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        t1.setLineWrap(true);
        t1.setRows(5);
        jScrollPane1.setViewportView(t1);

        b31.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b31.setText("SHOW OPTIONS");
        b31.setEnabled(false);
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });

        bg2.add(rb5);
        rb5.setFont(new java.awt.Font("Tahoma", 0, 31)); // NOI18N
        rb5.setText("OPTION 1");
        rb5.setEnabled(false);
        rb5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });

        bg2.add(rb6);
        rb6.setFont(new java.awt.Font("Tahoma", 0, 31)); // NOI18N
        rb6.setText("OPTION 2");
        rb6.setEnabled(false);
        rb6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });

        bg2.add(rb7);
        rb7.setFont(new java.awt.Font("Tahoma", 0, 31)); // NOI18N
        rb7.setText("OPTION 4");
        rb7.setEnabled(false);
        rb7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb7ActionPerformed(evt);
            }
        });

        bg2.add(rb8);
        rb8.setFont(new java.awt.Font("Tahoma", 0, 31)); // NOI18N
        rb8.setText("OPTION 3");
        rb8.setEnabled(false);
        rb8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb8ActionPerformed(evt);
            }
        });

        lsec.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lsec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lsec.setText("15");
        lsec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        b32.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b32.setText("SUBMIT");
        b32.setEnabled(false);
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });

        b33.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b33.setText("NEXT");
        b33.setEnabled(false);
        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(rb1)
                .addGap(165, 165, 165)
                .addComponent(rb2)
                .addGap(222, 222, 222)
                .addComponent(rb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb4)
                .addGap(171, 171, 171))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b17)))
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b18)
                    .addComponent(b11)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(b12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(b19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(b13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(b20))
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(b14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(b21))
                .addGap(52, 52, 52))
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(696, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b31)
                        .addGap(553, 553, 553)
                        .addComponent(lsec, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b32)
                        .addGap(438, 438, 438)
                        .addComponent(b33)
                        .addGap(179, 179, 179))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rb5, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb8, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb7, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb6, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel4)
                    .addContainerGap(1318, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1)
                    .addComponent(rb2)
                    .addComponent(rb3)
                    .addComponent(rb4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(b3)
                    .addComponent(b4)
                    .addComponent(b5)
                    .addComponent(b6)
                    .addComponent(b7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b8)
                    .addComponent(b9)
                    .addComponent(b10)
                    .addComponent(b11)
                    .addComponent(b12)
                    .addComponent(b13)
                    .addComponent(b14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b15)
                    .addComponent(b17)
                    .addComponent(b18)
                    .addComponent(b19)
                    .addComponent(b20)
                    .addComponent(b16)
                    .addComponent(b21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsec, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb5)
                    .addComponent(rb6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb7)
                    .addComponent(rb8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b32)
                    .addComponent(b33))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(jLabel4)
                    .addContainerGap(615, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
    b4.setEnabled(false);
    tf2.setText("4");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=4;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
    rb1.setEnabled(false);
    tf1.setText("city");
    b1.setEnabled(true);
    b2.setEnabled(true);
    b3.setEnabled(true);
    b4.setEnabled(true);
    b5.setEnabled(true);
    b6.setEnabled(true);
    b7.setEnabled(true);
    b8.setEnabled(true);
    b9.setEnabled(true);
    b10.setEnabled(true);
    b11.setEnabled(true);
    b12.setEnabled(true);
    b13.setEnabled(true);
    b14.setEnabled(true);
    b15.setEnabled(true);
    b16.setEnabled(true);
    b17.setEnabled(true);
    b18.setEnabled(true);
    b19.setEnabled(true);
    b20.setEnabled(true);
    b21.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
    rb2.setEnabled(false);
    tf1.setText("state");    // TODO add your handling code here:
    b1.setEnabled(true);
    b2.setEnabled(true);
    b3.setEnabled(true);
    b4.setEnabled(true);
    b5.setEnabled(true);
    b6.setEnabled(true);
    b7.setEnabled(true);
    b8.setEnabled(true);
    b9.setEnabled(true);
    b10.setEnabled(true);
    b11.setEnabled(true);
    b12.setEnabled(true);
    b13.setEnabled(true);
    b14.setEnabled(true);
    b15.setEnabled(true);
    b16.setEnabled(true);
    b17.setEnabled(true);
    b18.setEnabled(true);
    b19.setEnabled(true);
    b20.setEnabled(true);
    b21.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
    rb3.setEnabled(false);
    tf1.setText("awards");   // TODO add your handling code here:
    b1.setEnabled(true);
    b2.setEnabled(true);
    b3.setEnabled(true);
    b4.setEnabled(true);
    b5.setEnabled(true);
    b6.setEnabled(true);
    b7.setEnabled(true);
    b8.setEnabled(true);
    b9.setEnabled(true);
    b10.setEnabled(true);
    b11.setEnabled(true);
    b12.setEnabled(true);
    b13.setEnabled(true);
    b14.setEnabled(true);
    b15.setEnabled(true);
    b16.setEnabled(true);
    b17.setEnabled(true);
    b18.setEnabled(true);
    b19.setEnabled(true);
    b20.setEnabled(true);
    b21.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
    rb4.setEnabled(false);
    tf1.setText("sports");    // TODO add your handling code here:
    b1.setEnabled(true);
    b2.setEnabled(true);
    b3.setEnabled(true);
    b4.setEnabled(true);
    b5.setEnabled(true);
    b6.setEnabled(true);
    b7.setEnabled(true);
    b8.setEnabled(true);
    b9.setEnabled(true);
    b10.setEnabled(true);
    b11.setEnabled(true);
    b12.setEnabled(true);
    b13.setEnabled(true);
    b14.setEnabled(true);
    b15.setEnabled(true);
    b16.setEnabled(true);
    b17.setEnabled(true);
    b18.setEnabled(true);
    b19.setEnabled(true);
    b20.setEnabled(true);
    b21.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_rb4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
    b1.setEnabled(false);
    tf2.setText("1");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=1;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
    String db=tf1.getText();
    String question=tf2.getText();
    String option1=null;
    String option2=null;
    String option3=null;
    String option4=null;
    String correct=null;
    
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question="+question+";";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             option1=rs.getNString("option1");
             option2=rs.getNString("option2");
             option3=rs.getNString("option3");
             option4=rs.getNString("option4");
             correct=rs.getNString("correct");
             
         }
            
            rb5.setText(option1);
            rb6.setText(option2);
            rb7.setText(option3);
            rb8.setText(option4);
            tf3.setText(correct);
            timer = new Timer(1000, new ActionListener() {
         @Override
         public void actionPerformed(ActionEvent e) {
             
                          
             if(sec==0){
                 
                 try {
    File wavFile = new File("\\E:\\buzzer.wav\\");
    Clip clip = AudioSystem.getClip();
    clip.open(AudioSystem.getAudioInputStream(wavFile));
    clip.start();
} catch (Exception o) {
    System.out.println(o);
}
                 JOptionPane.showMessageDialog(rootPane, "Time's UP","Stopped",0);
                 sec=0;
                 timer.stop();
                  
             }else{
             
             sec--;
                       
             lsec.setText(""+sec);
             }
         }
     });
     
     timer.start();
        }
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    b31.setEnabled(false);
    rb5.setEnabled(true);
    rb6.setEnabled(true);
    rb7.setEnabled(true);
    rb8.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b31ActionPerformed

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
      
        timer.stop();
        String correct=tf3.getText();
    String selected=null;
    
    if(rb5.isSelected())
    {
        selected=rb5.getText();
    if(correct.equals(selected))
    {
        try {
    File wavFile = new File("\\E:\\correct.wav\\");
    Clip clip = AudioSystem.getClip();
    clip.open(AudioSystem.getAudioInputStream(wavFile));
    clip.start();
} catch (Exception o) {
    System.out.println(o);
}
        JOptionPane.showMessageDialog(this,"YOU ARE CORRECT");
        b33.setEnabled(true);
        b31.setEnabled(false);
    b32.setEnabled(false);
    rb8.setEnabled(false);
    rb6.setEnabled(false);
    rb5.setEnabled(false);
    rb7.setEnabled(false);
    rb8.setSelected(false);
    
    bg2.clearSelection();
     
              
    }
    else
    {
        try {
    File wavFile = new File("\\E:\\incorrect.wav\\");
    Clip clip = AudioSystem.getClip();
    clip.open(AudioSystem.getAudioInputStream(wavFile));
    clip.start();
} catch (Exception o) {
    System.out.println(o);
}
        
        JOptionPane.showMessageDialog(this,"INCORRECT");
        rb5.setEnabled(false);
        
    }
    }
    else 
        if(rb6.isSelected())
    {
        selected=rb6.getText();
    if(correct.equals(selected))
    {
        try {
    File wavFile = new File("\\E:\\correct.wav\\");
    Clip clip = AudioSystem.getClip();
    clip.open(AudioSystem.getAudioInputStream(wavFile));
    clip.start();
} catch (Exception o) {
    System.out.println(o);
}
        JOptionPane.showMessageDialog(this,"YOU ARE CORRECT");
        b33.setEnabled(true);
        b31.setEnabled(false);
    b32.setEnabled(false);
    rb8.setEnabled(false);
    rb6.setEnabled(false);
    rb5.setEnabled(false);
    rb7.setEnabled(false);
    rb8.setSelected(false);
    
    bg2.clearSelection();
     
              
    }
    else
    {
        try {
    File wavFile = new File("\\E:\\incorrect.wav\\");
    Clip clip = AudioSystem.getClip();
    clip.open(AudioSystem.getAudioInputStream(wavFile));
    clip.start();
} catch (Exception o) {
    System.out.println(o);
}
        JOptionPane.showMessageDialog(this,"INCORRECT");
        rb6.setEnabled(false);
    }
    }
        else 
            if(rb7.isSelected())
    {
        selected=rb7.getText();
    if(correct.equals(selected))
    {
        try {
    File wavFile = new File("\\E:\\correct.wav\\");
    Clip clip = AudioSystem.getClip();
    clip.open(AudioSystem.getAudioInputStream(wavFile));
    clip.start();
} catch (Exception o) {
    System.out.println(o);
}
        JOptionPane.showMessageDialog(this,"YOU ARE CORRECT");
        b33.setEnabled(true);
        b31.setEnabled(false);
    b32.setEnabled(false);
    rb8.setEnabled(false);
    rb6.setEnabled(false);
    rb5.setEnabled(false);
    rb7.setEnabled(false);
    rb8.setSelected(false);
    
    bg2.clearSelection();
     
              
    }
    else
    {
        try {
    File wavFile = new File("\\E:\\incorrect.wav\\");
    Clip clip = AudioSystem.getClip();
    clip.open(AudioSystem.getAudioInputStream(wavFile));
    clip.start();
} catch (Exception o) {
    System.out.println(o);
}
        JOptionPane.showMessageDialog(this,"INCORRECT");
        rb7.setEnabled(false);
    }
    }
    else
                if(rb8.isSelected())
    {
        selected=rb8.getText();
    if(correct.equals(selected))
    {
        try {
    File wavFile = new File("\\E:\\correct.wav\\");
    Clip clip = AudioSystem.getClip();
    clip.open(AudioSystem.getAudioInputStream(wavFile));
    clip.start();
} catch (Exception o) {
    System.out.println(o);
}
        JOptionPane.showMessageDialog(this,"YOU ARE CORRECT");
        b33.setEnabled(true);
        b31.setEnabled(false);
    b32.setEnabled(false);
    rb8.setEnabled(false);
    rb6.setEnabled(false);
    rb5.setEnabled(false);
    rb7.setEnabled(false);
    rb8.setSelected(false);
    
    bg2.clearSelection();
     
              
    }
    else
    {
        try {
    File wavFile = new File("\\E:\\incorrect.wav\\");
    Clip clip = AudioSystem.getClip();
    clip.open(AudioSystem.getAudioInputStream(wavFile));
    clip.start();
} catch (Exception o) {
    System.out.println(o);
}
        JOptionPane.showMessageDialog(this,"INCORRECT");
        rb8.setEnabled(false);
    }
    }
            bg2.clearSelection();
        // TODO add your handling code here:
    }//GEN-LAST:event_b32ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
    b32.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_rb5ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
    b32.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_rb6ActionPerformed

    private void rb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb8ActionPerformed
    b32.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_rb8ActionPerformed

    private void rb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb7ActionPerformed
    b32.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_rb7ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
    b2.setEnabled(false);
    tf2.setText("2");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=2;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
    b3.setEnabled(false);
    tf2.setText("3");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=3;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
    b5.setEnabled(false);
    tf2.setText("5");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=5;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
    b6.setEnabled(false);
    tf2.setText("6");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=6;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
    b7.setEnabled(false);
    tf2.setText("7");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=7;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
    b14.setEnabled(false);
    tf2.setText("14");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=14;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b14ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
    b21.setEnabled(false);
    tf2.setText("21");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=21;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b21ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
    b8.setEnabled(false);
    tf2.setText("8");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=8;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
    b9.setEnabled(false);
    tf2.setText("9");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=9;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
    b10.setEnabled(false);
    tf2.setText("10");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=10;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
    b11.setEnabled(false);
    tf2.setText("11");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=11;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
    b12.setEnabled(false);
    tf2.setText("12");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=12;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
    b13.setEnabled(false);
    tf2.setText("13");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=13;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b13ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
    b15.setEnabled(false);
    tf2.setText("15");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=15;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b15ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
    b17.setEnabled(false);
    tf2.setText("17");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=17;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b17ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
    b18.setEnabled(false);
    tf2.setText("18");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=18;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b18ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
    b19.setEnabled(false);
    tf2.setText("19");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=19;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b19ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
    b20.setEnabled(false);
    tf2.setText("20");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=20;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b20ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
    b16.setEnabled(false);
    tf2.setText("16");
    String db=tf1.getText();
    String question = null;
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)                       
    DriverManager.getConnection("jdbc:mysql://localhost:3307/ecg","root","abcd");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from "+db+" where question=16;";         
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())          
         {
        
             question=rs.getNString("statement");
         }
            
            t1.setText(question);}
            catch(ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    // TODO add your handling code here:
    b31.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_b16ActionPerformed

    private void b33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33ActionPerformed
        timer.stop();
        t1.setText("");
        rb5.setText("OPTION 1");
        rb6.setText("OPTION 2");
        rb7.setText("OPTION 3");
        rb8.setText("OPTION 4");
    b31.setEnabled(false);
    b32.setEnabled(false);
    rb8.setEnabled(false);
    rb6.setEnabled(false);
    rb5.setEnabled(false);
    rb7.setEnabled(false);
    rb8.setSelected(false);
    
    bg2.clearSelection();
     b33.setEnabled(false);
     sec=15;
     lsec.setText("15");    // TODO add your handling code here:
    }//GEN-LAST:event_b33ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QUIZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QUIZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QUIZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QUIZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QUIZ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b3;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lsec;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JTextArea t1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
}
